[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps =
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  bblanchon/ArduinoJson
  witnessmenow/UniversalTelegramBot