[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Thêm thư viện ở đây
lib_deps =
    olikraus/U8g2 @ ^2.35.9
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
monitor_speed = 115200
