[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Danh sách các thư viện cần thiết cho dự án
lib_deps = 
	; Thư viện kết nối nền tảng Blynk
	blynkkk/Blynk@^1.3.2
	
	; Thư viện đọc cảm biến DHT22 của Adafruit
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14
	
	; Thư viện điều khiển màn hình LED 7 thanh TM1637
	smougenot/TM1637